#import "@preview/wordometer:0.1.4": word-count

#let flo(term) = text(fill: red, [Flo: #term])

#let abstract-en = [
  In this work, we present improvements on the open-source software HAWEN, used to solve the wave problem in the frequency domain. The software can be used to both model the propagation of waves and solve the inverse problem, which consists in the reconstruction of the characteristics of the media in which the waves propagated. HAWEN relies on a discretization technique known as Hybridizable Discontinuous Galerkin (HDG) which makes heavy usage of operations on dense matrices. In this work, we will focus on improving the performance of the code by ensuring that these operations are executed efficiently. We will analyze the current state of libraries and compilers for the Fortran language. In particular, we will work with NVIDIA's NVHPC Toolkit and explore effective strategies for parallelization on GPU whilst maintaining the current combination of MPI and OpenMP parallelism. Another part will concern introducing a recently released GPU accelerated sparse solver, cuDSS, as alternative to the current one, MUMPS, to address the global linear system of HDG.
]

#let abstract-fr = [
  Dans ce travail, nous présentons des améliorations apportées au logiciel open source HAWEN, utilisé pour résoudre le problème des ondes dans le domaine fréquentiel. Le logiciel peut être utilisé à la fois pour modéliser la propagation des ondes et pour résoudre le problème inverse, qui consiste à reconstruire les caractéristiques du milieu dans lequel les ondes se sont propagées. HAWEN repose sur une technique de discrétisation connue sous le nome de "Hybridizable Discontinuous Galerkin" (HDG), qui fait un usage intensif d'opération sur des matrices denses. Dans ce travail, nous nous concentrerons sur l'amélioration des performances du code en veillant à ce que ces opérations soient exécutées efficacement. Nous analyserons l'état actuel des bibliothèques et des compilateurs pour le langage Fortran. En particulier, nous travaillerons avec le NVHPC Toolkit de NVIDIA et explorerons des stratégies efficaces de parallélisation sur GPU, tout en maintenant la combinaison actuelle de parallélisme MPI et OpenMP. Une autre partie portera sur l'introduction d'un solveur creux accéléré par GPU récemment publié, cuDSS, comme alternative à l'actuel, MUMPS, pour traiter le système linéaire global de la méthode HDG.
]
