#import "@preview/wordometer:0.1.4": word-count

#let flo(term) = text(fill: red, [Flo: #term])

#let abstract-en = [
  In this work, we present improvements on the free and open-source software @HAWEN:short, used to solve the wave problem in the frequency domain. The software can be used to both model the propagation of waves and solve the inverse problem, which consists in the reconstruction of the characteristics of the media in which the waves propagated. @HAWEN:short relies on a discretization technique known as "@HDG:long" (@HDG:short) which makes heavy usage of operations on dense matrices. In this work, we will focus on improving the performance of the code by ensuring that these operations are executed efficiently. We will analyze the current state of libraries and compilers for the Fortran language. In particular, we will work with NVIDIA's NVHPC Toolkit and explore effective strategies for parallelization on @GPU:short:pl whilst maintaining the current combination of @MPI:short and OpenMP parallelism. Another part will concern introducing a recently released @GPU:short accelerated sparse solver, cuDSS, as alternative to the current one, @MUMPS:short, to address the global linear system of @HDG:short.
]

#let abstract-fr = [
  Dans ce travail, nous présentons des améliorations apportées au logiciel libre @HAWEN:short, utilisé pour résoudre le problème des ondes dans le domaine fréquentiel. Le logiciel peut être utilisé à la fois pour modéliser la propagation des ondes et pour résoudre le problème inverse, qui consiste à reconstruire les caractéristiques du milieu dans lequel les ondes se sont propagées. @HAWEN:short repose sur une technique de discrétisation connue sous le nom de "@HDG:long" (@HDG:short), qui fait un usage intensif d'opérations sur des matrices denses. Dans ce travail, nous nous concentrerons sur l'amélioration des performances du code en veillant à ce que ces opérations soient exécutées efficacement. Nous analyserons l'état actuel des bibliothèques et des compilateurs pour le langage Fortran. En particulier, nous travaillerons avec le le kit de développement NVHPC de NVIDIA et explorerons des stratégies efficaces de parallélisation sur @GPU:short:pl, tout en maintenant la combinaison actuelle de parallélisme @MPI:short et OpenMP. Une autre partie portera sur l'introduction d'un solveur creux accéléré par @GPU:short récemment publié, cuDSS, comme alternative à l'actuel, @MUMPS:short, pour traiter le système linéaire global de la méthode @HDG:short.
]
