#let acknowledgements = [
  I would like to thank my supervisors, Prof. Christophe Picard, for giving me the opportunity to embark in this journey. His teachings sparked my passion for GPU computing and gave me the confidence to tackle such challenges. My deepest gratitude goes to Florian Faucher and Marc Fuentes, with whom I worked closely throughout these six months. This internship allowed me to explore several topics I had no prior experience with, it allowed me to learn so much and for this I am very thankful. I was fortunate to find such amazing people, who kindly and patiently explained me new concepts and where always available to help me or to work together in finding solutions. I could never have done it alone: our many discussions where always both insightful and very enjoyable. I sincerely hope we could still continue collaborating in the future.

  I would also like to acknowledge the freedom and opportunities I was given as well as the computational resources that made this work possible #footnote[Experiments presented in this thesis were carried out using the PlaFRIM experimental testbed, supported by Inria, CNRS (LABRI and IMB), Université de Bordeaux, Bordeaux INP and Conseil Régional d’Aquitaine (see https://www.plafrim.fr).]#super[,]#footnote[This work benefited from access to the computing resources of the “CALI 3” cluster. This cluster is operated and hosted by the University of Limoges. It is part of the HPC network in the Nouvelle-Aquitaine Region, financed by the State and the Region.]. The very flexible work environment also certainly helped me push through all the many dead ends I encountered. I am also very thankful to Mathew Colgrove from NVIDIA, who always answered my questions on the NVHPC compilers and guided me through any unexpected behavior I encountered. Finally, I would like to acknowledge the Typst community and its developers, whose work and support helped me achieve a high-quality final result for my report.

  I am deeply grateful to all the friends with whom I shared this university course, in particular Dennis Gobbi, Miriam Lamari, Greta Tumiatti and Andrea Mirenda; you all always helped me clarify anything that left me puzzled. This journey hasn't been easy and studying with you has certainly made these past two years more enjoyable. Working on projects together has been a breath of fresh air compared to the other academic experiences, and I hope we will continue to stay in touch and collaborate.

  Finally, I would like to extend my heartfelt thanks to my family and Andrea Comito, who always supported me (and endured) me during these years. Your encouragement means everything to me, thank you! I am also indebted to my high school teacher Nirvana Dainese: it was thanks to her that I learned to appreciate mathematics. Without her influence, I might not have had the confidence to pursue an internship so strongly rooted in mathematics.
]
