#let flo(term, color: red) = {
  text(color, [Flo: #term])
}

#let edu = text.with(fill: green)

= Conclusions and Future Works <conclusions>

In this work we have investigated how to improve the performance of the free and open source software "HAWEN" that solves forward and inverse wave problems. The discretization uses the @HDG:long method, which leads to dense (relatively small) matrix operations before the resolution of a large-scale sparse linear system. We have seen different approaches for the acceleration of the matrix creation and the resolution of the large scale linear system in @HAWEN. We have defined a good workflow for future performance oriented work and the first pillars necessary to introduce more @GPU offloading in the program have been planted. More specifically, we addressed problems in the language standard adherence, made the build system more flexible, explored different device offloading strategies, and added a @GPU#[-accelerated] sparse solver as alternative to the current one. Following the approaches presented here, it is now possible to introduce efficient @GPU parallelism of certain subroutines in a self-contained manner, as shown in our first benchmarks with the NVHPC Toolkit. We expect this work to save time and resources in the near future and enhance the development experience of the researchers working on it. We also expect it to open the door for future more significant improvements to the runtime.

Taking advantage of Fortran's very thorough system for defining custom floating point numbers, it should be possible to optimize some operations that do not require a high precision. The work on precision is particularly important for @GPU computing, where current trends encourage the usage of the lowest possible precision for each application. #cite(<x-OzakiII>, form: "prose") introduce an interesting approach that could be extended to other applications that involves the computation of high precision float in lower precision (FP64 results by only using INT8 operations). This approach is particularly useful on @GPU but can also prove effective on @CPU:pl that support vector operations.


Given the reliance on @BLAS and @LAPACK operations for a good amount of the most computational intensive parts of the code, exploring platform agnostic ways of accelerating these operations with @GPU:pl would certainly prove very useful. For that purpose, #cite(<x-XKBlas>, form: "prose") developed a library called "XKBlas" which serves exactly this purpose. While integrating directly at the moment presents some blockers, it is something that could be done in the near future.

Being the @HDG algorithm embarrassingly parallel in respect to each cell, completely offloading it to @GPU should be possible, the code currently contains too much branching to make this approach viable but we cannot exclude that rewriting it in a simpler and more efficient manner could enable this. Currently, the main constraint of this approach is the memory consumption, being, generally, @RAM more readily available than @VRAM, this could also hinder a complete parallelization attempt on @GPU. In this context, systems that take a unified approach to memory -- for instance the products currently offered by Apple on the consumer side, but also the ARM-based servers released by NVIDIA -- might prove as the best approach going forward. #cite(<x-GPUHDG>, form: "prose") selected @GPU:pl as the platform of choice for @HDG due to their higher memory bandwidth, suggesting that the same could be applicable to @HAWEN and the tradeoff between memory bandwidth and memory capacity could still be advantageous. Loading smaller chunks of data in memory at the cost of more computation might be beneficial if that enables greater parallelization opportunities. This kind of analysis will require a different set of tools and profilers, such as Linaro's DDT and MAP @x-Linaro.

Finally, the @GPU code present in @HAWEN does not currently fully take advantage of the asynchronous nature of accelerators, meaning that when @GPU code is executed, the @CPU always waits for its result. This is an area where we could certainly improve by further modularizing the different algorithms.

// Finally, the program currently uses very large amounts of memory, limiting the scalability for larger use cases. An analysis on memory usage is something that will require a different approach and a different set of tools but will be necessary in the future.